apiVersion: v1
kind: Secret
metadata:
  name: db-secret-team2a
  namespace: container-team2a
type: Opaque
stringData:
  DB_USER: team2a
  DB_PASSWORD: supersecurepasswordteam2a
  DB_NAME: appdbteam2a
