apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-web
  namespace: container-team2a
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-web
  template:
    metadata:
      labels:
        app: app-web
    spec:
      containers:
        - name: app-web
          image: ricardomf01/app-web:1.0
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: svc-db
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret-team2a
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret-team2a
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secret-team2a
                  key: DB_NAME
