apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: container-team2a
spec:
  selector:
    app: app-web
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  type: ClusterIP
